#coding=utf-8
"""
Django settings for sclm project.

Generated by 'django-admin startproject' using Django 1.8.7.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""


# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os
import sys

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
# 将部分的源码路径增加至工程中
#sys.path.insert(0, os.path.join(BASE_DIR, 'extra_apps'))
sys.path.insert(0, os.path.join(BASE_DIR, 'templates'))
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

from django.conf.global_settings import TEMPLATE_CONTEXT_PROCESSORS as TCP

TEMPLATE_CONTEXT_PROCESSORS = TCP + (
    'django.core.context_processors.request',
)

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'ylfv1sw_9#3-!teyk^pkz)c0+^#pd0k+8u5uzghp*to^#$vz3h'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

MEDIA_URL = '/MediaFile/'
MEDIA_ROOT = os.path.join(BASE_DIR , 'Mediafile')
#MEDIA_ROOT = '/home/liujie/mineoss'

# Application definition

INSTALLED_APPS = (
    'filer',
    'suit',
    'easy_thumbnails',
    'mptt',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'blog',
    )

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
)

ROOT_URLCONF = 'sclm.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [(os.path.join(BASE_DIR,'templates'))],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

TEMPLATE_DIRS = (
                    os.path.join(os.path.dirname(__file__),'templates'),
)


WSGI_APPLICATION = 'sclm.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

DATABASES = {
 #   'default': {
 #       'ENGINE': 'django.db.backends.sqlite3',
 #       'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
  #  }
	 'default':{
        'ENGINE': 'django.db.backends.mysql',
        'NAME': "sclm",
        'USER': 'root',
        'PASSWORD': 'liujie',
        'HOST': '127.0.0.1',
}

}


# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'zh-CN'
TIME_ZONE = 'Asia/Shanghai'
USE_I18N = True
USE_L10N = False
USE_TZ = False
DATETIME_FORMAT = 'Y-m-d H:i:s'
DATE_FORMAT = 'Y-m-d'

THUMBNAIL_HIGH_RESOLUTION = True

SUIT_CONFIG = {
    'ADMIN_NAME': '三草两木',
    'LIST_PER_PAGE': 20,
    'MENU': (

            # Keep original label and models
            'sites',
            {'app': 'filer', 'label': 'filer', 'icon':'icon-leaf'},

        ),
  }

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR,'Static')
'''
STATICFILES_DIRS = (os.path.join(BASE_DIR,'admin'),os.path.join(BASE_DIR,'suit'),os.path.join(BASE_DIR,'file'),
                    os.path.join(BASE_DIR,'cms'),
                    os.path.join(BASE_DIR,'mptt'),
                    os.path.join(BASE_DIR,'Static'),
                    )
'''

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'file': {
            'level': 'DEBUG',
            'class': 'logging.FileHandler',
            'filename': './debug.log',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['file'],
            'level': 'DEBUG',
            'propagate': True,
        },
    },
}
